# Generated by Django 6.1.1 on 2026-10-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, verbose_name='Evento')),
                ('recipient', models.CharField(max_length=200, verbose_name='Destinatário')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(default='Pedro & Sabrina', max_length=200, verbose_name='Nome do Casal')),
                ('wedding_date', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Casamento')),
                ('main_quote', models.TextField(default='Nossa história continua aqui.', verbose_name='Frase Principal')),
                ('our_story', models.TextField(blank=True, verbose_name='Nossa História')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='Local do Casamento')),
                ('location_address', models.TextField(blank=True, verbose_name='Endereço')),
                ('location_map_link', models.URLField(blank=True, verbose_name='Link do Mapa')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Foto da Capa')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Foto da História')),
                ('pix_key', models.CharField(blank=True, max_length=200, verbose_name='Chave PIX')),
                ('pix_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Recebedor PIX')),
                ('pix_city', models.CharField(blank=True, max_length=200, verbose_name='Cidade PIX')),
                ('pix_qrcode', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='QR Code PIX')),
                ('pix_text', models.TextField(default='Se quiser contribuir de outra forma...', verbose_name='Texto do PIX')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail para Notificações')),
                ('show_messages', models.BooleanField(default=True, verbose_name='Exibir Mensagens dos Convidados')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Imagem')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade Total')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade Reservada')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('partially', 'Parcialmente Reservado'), ('reserved', 'Totalmente Reservado'), ('hidden', 'Oculto')], default='available', max_length=20, verbose_name='Status')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='registry.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Nome do Convidado')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('is_message_approved', models.BooleanField(default=False, verbose_name='Mensagem Aprovada')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='registry.gift', verbose_name='Presente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
