# Generated by Django 6.1.1 on 2026-10-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoria e seus Presentes', 'verbose_name_plural': 'Categorias e seus Presentes'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Textos e Galeria do Site', 'verbose_name_plural': 'Textos e Galeria do Site'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='site_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='registry.sitesettings'),
        ),
    ]
