version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wedding
      - POSTGRES_USER=wedding_user
      - POSTGRES_PASSWORD=wedding_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data:
